### ISSUE TITLE
Apostrofo nel cognome

### ISSUE THREAD

**Issue by AndreSfo** [DavidePastore/AndroidCF#30]
Io ho risolto aggiungendo al metodo "eliminaSpaziBianchi" anche il controllo per rimuovere gli apostrofi ( .replaceAll("\'","") ).

Volevo segnalarlo. Può essere corretto?

**Comment by DavidePastore** [comment]
Ciao @AndreSfo . Grazie per aver aperto questa issue. Se sai già come risolvere il problema, puoi aprire una Pull Request con il tuo fix, altrimenti lo farò io appena ho un po' di tempo a disposizione. 😄

**Comment by AndreSfo** [comment]
Ciao,
figurati. Grazie a te che mi hai semplificato il "controllo"! ;-)
Per la fix io ho fatto come ho scritto nel commento precedente.

Per la pull lascio a te che non vorrei fare danni! :)
